config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask

  end

  def answer

    @ask = params[:name]

    if @ask == 'I am going to work'
      @response = 'Great!'
    elsif @ask.include? '?'
      @response = 'Silly question, get dressed and go to work!'
    else
      @response = 'I don\'t care, get dressed and go to work!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Questions</h1>

<div class="question">
  <h2> <%= @ask %> </h2>
  <h3>- You</h3>
</div>

<div class="response">
  <h2> <%= @response %> </h2>
  <h3>- Your coach</h3>
</div

<div class="link">
  <h4> <%=link_to "ask new question", ask_path %> </h4>
</div>

app/views/questions/ask.html.erb
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>


<form action="/answer" method="get">
   <input type="text" name="name">
  <input type="submit" value="Ask!">
</form>

<p><%= @ask %></p>